<?php

namespace Jimdo\JimFlow\PrintTicketBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GoogleAuthTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoogleAuthTokenRepository extends EntityRepository
{
}
