<?php

namespace Jimdo\JimFlow\PrintTicketBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TicketTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketTypeRepository extends EntityRepository
{
    /**
     * @param $id
     * @return array
     */
    public function findBeingFallbackAndNotBeingEntity($id)
    {
        $queryBuilder = $this->createQueryBuilder('t');

        $queryBuilder->add('select', 'tt');
        $queryBuilder->add('from', '\Jimdo\JimFlow\PrintTicketBundle\Entity\TicketType tt');
        $queryBuilder->andWhere('tt.id != :id');
        $queryBuilder->andWhere('tt.isFallback = 1');
        $queryBuilder->setParameter('id', $id);

        $query = $queryBuilder->getQuery();

        return $query->getResult();
    }

}
