printer:
    pattern:  /ticket
    defaults: { _controller: "JimdoJimFlowPrintTicketBundle:Print:printticket" }

print_story:
    pattern:  /story
    defaults: { _controller: "JimdoJimFlowPrintTicketBundle:Print:printstory" }


oauth_test:
    pattern:  /oauthtest
    defaults: { _controller: "JimdoJimFlowPrintTicketBundle:Print:oauth" }

