<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120627113758 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE TicketType (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, background_color VARCHAR(6) NOT NULL, is_background_filled TINYINT(1) DEFAULT NULL, is_fallback TINYINT(1) DEFAULT NULL, UNIQUE INDEX UNIQ_2DA339115E237E06 (name), PRIMARY KEY(id)) ENGINE = InnoDB");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE TicketType");
    }
}
