services:

  jimdo.google.client.factory:
    class: Jimdo\JimFlow\PrintTicketBundle\Lib\Google\GoogleClientFactory
    arguments:
      - %google.client_id%
      - %google.client_secret%
      - @router

  google.google_client:
    class: Google_Client
    factory_service: jimdo.google.client.factory
    factory_method: createClient

  jimdo.google.accesstoken:
    class: Jimdo\JimFlow\PrintTicketBundle\Lib\Google\AccessToken
    arguments:
      - @google.google_client
      - @zend.cache.google_auth
      - @jimdo.google_auth_token_entity_repository

  zend.cache.google_auth:
    class: Zend\Cache\Storage\Adapter\Filesystem
    factory_class: Zend\Cache\StorageFactory
    factory_method: factory
    arguments:
      - {adapter: {name:'Filesystem', options: {ttl: 86400}}}

  jimdo.google.client.gcp:
    class: Jimdo\JimFlow\PrintTicketBundle\Lib\Google\Client
    arguments:
      - @jimdo.buzz.browser
      - @jimdo.google.accesstoken

  jimdo.gcp.client:
    class: Jimdo\JimFlow\PrintTicketBundle\Lib\Google\GCP\Client
    arguments:
      - @jimdo.google.client.gcp
