<?php

namespace Jimdo\JimkanbanBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TicketTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketTypeRepository extends EntityRepository
{
}